### ISSUE TITLE
Older csproj files get 'corrupted'.

### ISSUE THREAD

**Issue by TiltonJH** [CloudNimble/PackageReferenceUpgrader#1]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 1.0.0

### Description
Older csproj files get 'corrupted'.

### Steps to recreate
1. open an old csproj (created with VS 2015 or before that)
2. make the upgrade
3. have a look at the differences

### Current behavior
**Before:**
`<?xml version="1.0" encoding="utf-8"?>`
`<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`
`  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />`
`<PropertyGroup>`
`...`

**After:**
`<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`
`  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />`
`<PropertyGroup>`
`...`
- the xml header is removed, why?
- the `ToolsVersion` is not upgraded -> msbuild 14 or before can not handle `<PackageReference Include="..." Version="..." />`

### Expected behavior
After:
`<?xml version="1.0" encoding="utf-8"?>`
`<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`
`  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />`
`<PropertyGroup>`
`...`

However, IMHO getting into upgrading csproj to VS2017 (`ToolsVersion="15.0"`) might be difficult. Even VS2017 does not handle that entirely correct for old projects (removing/adding/updating tags). 

So may be only enable the upgrade for VS2015 (`ToolsVersion="15.0"`) projects?

**Comment by robertmclaws** [comment]
This is great feedback. @terrajobst, how do you think I should handle this? Upgrade the ToolsVersion too? Or something else?

**Comment by terrajobst** [comment]
AFAIK `ToolsVersion` is ignored entirely by MSBuild. /cc @dsplaisted @davkean

**Comment by TiltonJH** [comment]
Might be, but Visual Studio does care for it. For example VS2015 does not open a csproj with `ToolsVersion="15.0"`.

**Comment by terrajobst** [comment]
In that case I think it's a good idea to update the `ToolsVersion`.

**Comment by PhilPJL** [comment]
The tool also changes the encoding which causes problem when diff'ing.
It also strips out the .net compiler import statements - not sure if that's correct or not, I'm expecting not.

![image](https://user-images.githubusercontent.com/271656/31547789-88a16d72-b020-11e7-988b-bd82c4bc2fd6.png)

**Comment by PhilPJL** [comment]
Also it deletes the packages.config from disk but not from source control (TFS).

**Comment by robertmclaws** [comment]
@philpjl, if you could please open separate issues for your posts so I can track them separately, I will get a new release out this weekend.

Thanks!

**Comment by robertmclaws** [comment]
I believe I addressed your issue in [Build 1.0.1](http://vsixgallery.com/extensions/bae2a4ae-be17-4f34-be32-f7f103918589/NuGet%20PackageReference%20Upgrader%20v1.0.1.vsix). If you could please verify the fix for me, I'll release it to everyone else. Thanks!

**Comment by TiltonJH** [comment]
Took me a while, but I can confirm that this issue is resolved.

Great Work! Thx!


PS: I stated that VS 2015 does not open `.csproj`-files with `ToolsVersion="15.0"`. Well it seems I was wrong.
I just tried that again, and VS 2015 opens. However, the packages references get shown as odd missing files. So I wish it wouldn't open. It can not compile successful anyway.
