### ISSUE TITLE
packages.config deleted from disk but not from source control

### ISSUE THREAD

**Issue by PhilPJL** [CloudNimble/PackageReferenceUpgrader#2]
### Installed product versions
- Visual Studio: 2017 (15.5.0)

### Description
When running the tool packages.config deleted from disk but not from source control - TFS in my case.

Should be marked as deleted from TFS.

**Comment by robertmclaws** [comment]
I believe I addressed your issue in [Build 1.0.1](http://vsixgallery.com/extensions/bae2a4ae-be17-4f34-be32-f7f103918589/NuGet%20PackageReference%20Upgrader%20v1.0.1.vsix). If you could please verify the fix for me, I'll release it to everyone else. Thanks!

**Comment by PhilPJL** [comment]
Can't install it. 
[VSIXInstaller_ee9b71f8-74b7-4e6f-9b31-76d359610b56.log](https://github.com/CloudNimble/PackageReferenceUpgrader/files/1385804/VSIXInstaller_ee9b71f8-74b7-4e6f-9b31-76d359610b56.log)

![image](https://user-images.githubusercontent.com/271656/31588891-5c0b306e-b1f0-11e7-847a-81cca12f9f77.png)

**Comment by robertmclaws** [comment]
The log is showing that Visual Studio errored out while trying to grab the version number. With the number of issues you are having, you might consider repairing Visual Studio. Seems like there might be something else about your system configuration that is getting in the way.

**Comment by robertmclaws** [comment]
Haven't heard anything back, so I'm closing out this issue for now. If you have any problems, please feel free to re-open.

**Comment by PhilPJL** [comment]
Sorry for not replying, was on holiday.  Just tried 1.0.1.  Same/similar behaviour.  packages.config is deleted from the project but is marked as edited not deleted when using TFS 2012.  Not a big problem I can delete it from source control manually.
