### ISSUE TITLE
Project file encoding changed

### ISSUE THREAD

**Issue by PhilPJL** [CloudNimble/PackageReferenceUpgrader#3]
### Installed product versions
- Visual Studio: 2017 (15.5.0)

### Description
The tool changes the encoding which causes problem when diff'ing.

![snip](https://user-images.githubusercontent.com/271656/31549192-5467eaf4-b025-11e7-9f59-17e19368cf5c.png)

**Comment by robertmclaws** [comment]
I believe I addressed your issue in [Build 1.0.1](http://vsixgallery.com/extensions/bae2a4ae-be17-4f34-be32-f7f103918589/NuGet%20PackageReference%20Upgrader%20v1.0.1.vsix). If you could please verify the fix for me, I'll release it to everyone else. Thanks!
