### ISSUE TITLE
Command does not show up in dialog box

### ISSUE THREAD

**Issue by robertgins** [CloudNimble/PackageReferenceUpgrader#8]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 0.1.33

After installing, I expected to see a menu option on the right click dialog for packages.config files, I do not see that. No errors in VStudio, Tried with packagereferences as the default and without.

**Comment by robertmclaws** [comment]
I'm sorry, but version 0.1.33 is referring to this add-in, which is not ours: https://marketplace.visualstudio.com/items?itemName=TaylorSouthwickMSFT.NuGetPackagetoProjectjsonConverter. You can report this issue [on their GitHub repo](https://github.com/twsouthwick/NuGetPackageConfigConverter/issues).

You're welcome to uninstall that version and try this one, which is ours: https://marketplace.visualstudio.com/items?itemName=CloudNimble.NuGetPackageReferenceUpgrader

If you do try ours and run into any issues, please feel free to let me know.

HTH!
